//
//  ZEPTO-8 — Fantasy console emulator
//
//  Copyright © 2016–2024 Sam Hocevar <sam@hocevar.net>
//
//  This program is free software. It comes without any warranty, to
//  the extent permitted by applicable law. You can redistribute it
//  and/or modify it under the terms of the Do What the Fuck You Want
//  to Public License, Version 2, as published by the WTFPL Task Force.
//  See http://www.wtfpl.net/ for more details.
//

#include <cctype>
#include <cstring>

#define lpico8lib_c
#define LUA_LIB

#include "lua.h"

#include "lauxlib.h"
#include "llimits.h"
#include "lobject.h"

#include "trigtables.h"

static int pico8_max(lua_State *l) {
    lua_pushnumber(l, lua_Number::max(lua_tonumber(l, 1), lua_tonumber(l, 2)));
    return 1;
}

static int pico8_min(lua_State *l) {
    lua_pushnumber(l, lua_Number::min(lua_tonumber(l, 1), lua_tonumber(l, 2)));
    return 1;
}

static int pico8_mid(lua_State *l) {
    lua_Number x = lua_tonumber(l, 1);
    lua_Number y = lua_tonumber(l, 2);
    lua_Number z = lua_tonumber(l, 3);
    lua_pushnumber(l, x > y ? y > z ? y : lua_Number::min(x, z)
                            : x > z ? x : lua_Number::min(y, z));
    return 1;
}

static int pico8_ceil(lua_State *l) {
    lua_pushnumber(l, lua_Number::ceil(lua_tonumber(l, 1)));
    return 1;
}

static int pico8_flr(lua_State *l) {
    lua_pushnumber(l, lua_Number::floor(lua_tonumber(l, 1)));
    return 1;
}

static lua_Number sin_helper(lua_Number x) {
    // Reduce angle to 0x0 … 0x0.3fff, with the following PICO-8 rules:
    //  - sin(x) = -sin(x + 0.5)
    //  - sin(x) equals sin(~x) rather than sin(-x)
    //  - the last two bits are rounded
    // We use a lookup table of sin(x)-4x generated by PICO-8 to ensure
    // that we get the exact same results.
    auto a = ((x.bits() & 0x4000 ? ~x : x).bits() & 0x3fff) + 2;
    auto ret = lua_Number::frombits((a >> 2 << 4) + sintable[a >> 2]);
    return x.bits() & 0x8000 ? ret : -ret;
}

static int pico8_cos(lua_State *l) {
    lua_pushnumber(l, sin_helper(lua_tonumber(l, 1) - lua_Number::frombits(0x4000)));
    return 1;
}

static int pico8_sin(lua_State *l) {
    lua_pushnumber(l, sin_helper(lua_tonumber(l, 1)));
    return 1;
}

static int pico8_atan2(lua_State *l) {
    lua_Number x = lua_tonumber(l, 1);
    lua_Number y = lua_tonumber(l, 2);
    int32_t bits = 0x4000;
    if (x) {
        // Use std::abs() instead of fix32::abs() to emulate PICO-8’s behaviour
        // with e.g. atan2(0x8000, 0x8000.0001)
        auto q = (std::abs(int64_t(y.bits())) << 16) / std::abs(int64_t(x.bits()));
        if (q > 0x10000)
            bits -= atantable[(int64_t(1) << 32) / q >> 5];
        else
            bits = atantable[q >> 5];
    }
    if (x.bits() < 0) bits = 0x8000 - bits;
    if (y.bits() > 0) bits = -bits & 0xffff;
    // Emulate a bug in PICO-8 with e.g. atan2(1, 0x8000)
    if (x && y.bits() == int32_t(0x80000000)) bits = -bits & 0xffff;
    lua_pushnumber(l, lua_Number::frombits(bits));
    return 1;
}

static int pico8_sqrt(lua_State *l) {
    int64_t root = 0, x = int64_t(lua_tonumber(l, 1).bits()) << 16;
    if (x > 0) {
        // Square root by abacus algorithm, Martin Guy @ UKC, June 1985.
        // From a book on programming abaci by Mr C. Woo.
        // Observing a PICO-8 JavaScript export shows the same algorithm.
        for (int64_t a = int64_t(1) << 46; a; a >>= 2, root >>= 1) {
            if (x >= a + root) {
                x -= a + root;
                root += a << 1;
            }
        }
    }
    lua_pushnumber(l, lua_Number::frombits(root));
    return 1;
}

static int pico8_abs(lua_State *l) {
    lua_pushnumber(l, lua_Number::abs(lua_tonumber(l, 1)));
    return 1;
}

static int pico8_sgn(lua_State *l) {
    lua_pushnumber(l, cast_num(lua_tonumber(l, 1).bits() >= 0 ? 1.0 : -1.0));
    return 1;
}

static int pico8_band(lua_State *l) {
    lua_pushnumber(l, lua_tonumber(l, 1) & lua_tonumber(l, 2));
    return 1;
}

static int pico8_bor(lua_State *l) {
    lua_pushnumber(l, lua_tonumber(l, 1) | lua_tonumber(l, 2));
    return 1;
}

static int pico8_bxor(lua_State *l) {
    lua_pushnumber(l, lua_tonumber(l, 1) ^ lua_tonumber(l, 2));
    return 1;
}

static int pico8_bnot(lua_State *l) {
    lua_pushnumber(l, ~lua_tonumber(l, 1));
    return 1;
}

static int pico8_shl(lua_State *l) {
    lua_pushnumber(l, lua_tonumber(l, 1) << int(lua_tonumber(l, 2)));
    return 1;
}

static int pico8_lshr(lua_State *l) {
    lua_pushnumber(l, lua_Number::lshr(lua_tonumber(l, 1), int(lua_tonumber(l, 2))));
    return 1;
}

static int pico8_shr(lua_State *l) {
    lua_pushnumber(l, lua_tonumber(l, 1) >> int(lua_tonumber(l, 2)));
    return 1;
}

static int pico8_rotl(lua_State *l) {
    lua_pushnumber(l, lua_Number::rotl(lua_tonumber(l, 1), int(lua_tonumber(l, 2))));
    return 1;
}

static int pico8_rotr(lua_State *l) {
    lua_pushnumber(l, lua_Number::rotr(lua_tonumber(l, 1), int(lua_tonumber(l, 2))));
    return 1;
}

static int pico8_tostr(lua_State *l) {
    char buffer[20];
    char const *s = buffer;

    uint16_t flags = 0;
    if (lua_isboolean(l, 2)) {
        flags = lua_toboolean(l, 2) ? 1 : 0;
    }
    else if (lua_isnumber(l, 2)) {
        flags = lua_tointeger(l, 2);
    }

    switch (lua_type(l, 1))
    {
        case LUA_TNONE:
            // PICO-8 0.2.2 changelog: tostr() returns "" instead of nil
            buffer[0] = '\0';
            break;
        case LUA_TNUMBER: {
            lua_Number x = lua_tonumber(l, 1);
            if (flags) {
                uint32_t b = (uint32_t)x.bits();
                if ((flags & 0x3) == 0x3) {
                    sprintf(buffer, "0x%04x%04x", (b >> 16) & 0xffff, b & 0xffff);
                }
                else if ((flags & 0x2) == 0x2) {
                    sprintf(buffer, "%d", b);
                }
                else {
                    sprintf(buffer, "0x%04x.%04x", (b >> 16) & 0xffff, b & 0xffff);
                }
            } else {
                lua_number2str(buffer, x);
            }
            break;
        }
        case LUA_TSTRING:
            lua_pushvalue(l, 1);
            return 1;
        case LUA_TBOOLEAN: s = lua_toboolean(l, 1) ? "true" : "false"; break;
        case LUA_TUSERDATA: // for non-standard use
        case LUA_TTABLE:
            // PICO-8 0.1.12d changelog: “__tostring metatable method
            // observed by tostr() / print() / printh()”
            if (luaL_callmeta(l, 1, "__tostring")) {
                luaL_tolstring(l, 1, NULL);
                return 1;
            }
            [[fallthrough]];
        case LUA_TFUNCTION:
            // PICO-8 0.1.12d changelog: “tostr(x,true) can also be used to view
            // the hex value of functions and tables (uses Lua's tostring)”
            if (flags) {
                luaL_tolstring(l, 1, NULL);
                return 1;
            }
            [[fallthrough]];
        default: sprintf(buffer, "[%s]", luaL_typename(l, 1)); break;
    }
    lua_pushstring(l, s);
    return 1;
}

static int pico8_tonum(lua_State *l) {
    lua_Number ret;
    uint16_t flags = lua_gettop(l) >= 2 ? lua_tointeger(l, 2) : 0;
    switch (lua_type(l, 1))
    {
        case LUA_TSTRING: {
            size_t slen;
            char const *s = lua_tolstring(l, 1, &slen);
            if (flags & 0x1) {
                char const* start = slen <= 8 ? s : s + slen - 8;
                char buffer[9];
                size_t i;
                for (i = 0; start[i] != '\0'; ++i) {
                    buffer[i] = isxdigit(start[i]) ? start[i] : '0';
                }
                buffer[i] = '\0';

                uint32_t bits = strtol(buffer, NULL, 16);
                if (flags & 0x2)
                    lua_pushnumber(l, lua_Number::frombits(bits));
                else
                    lua_pushnumber(l, (lua_Number) bits);
                return 1;
            }
            else if (flags & 0x2) {
                uint32_t bits = strtol(s, NULL, 10);
                lua_pushnumber(l, lua_Number::frombits(bits));
                return 1;
            }
            
            if (!luaO_str2d(s, strlen(s), &ret)) {
                if (flags & 0x4)
                    ret = 0;
                else
                    return 0; // If parsing failed, PICO-8 returns nothing (by default)
            }
            break;
        }
        case LUA_TNUMBER: ret = lua_tonumber(l, 1); break;
        // PICO-8 0.2.3 changelog: “tonum(boolean_value) returns 1 or 0 instead of nil”
        case LUA_TBOOLEAN: {
            int val = lua_toboolean(l, 1) ? 1 : 0;
            if (flags & 0x2)
                ret = lua_Number::frombits(val);
            else
                ret = (lua_Number) val;
            break;
        }
        default: return 0;
    }
    lua_pushnumber(l, ret);
    return 1;
}

static int pico8_chr(lua_State *l) {
    size_t numargs = lua_gettop(l);
    luaL_Buffer buf;
    char *p = luaL_buffinitsize(l, &buf, numargs);
    for (size_t i = 0; i < numargs; i++) {
        p[i] = (char)(uint8_t)lua_tonumber(l, i + 1);
    }
    luaL_pushresultsize(&buf, numargs);
    return 1;
}

static int pico8_ord(lua_State *l) {
    size_t len;
    int n = 0;
    int count = 1;
    if (!lua_isstring(l, 1)) {
        lua_pushnil(l);
        return 1;
    }
    char const *s = luaL_checklstring(l, 1, &len);
    if (!lua_isnone(l, 3))
        count = int(lua_tonumber(l, 3));
    if (!lua_isnone(l, 2))
        n = int(lua_tonumber(l, 2)) - 1;
    if (count < 1)
        return 0;
    // min stack is only 20. This could be a much longer string
    lua_checkstack(l, count);
    for (int i = 0; i < count; ++i) {
        size_t idx = n + i;
        if (idx >= 0 && idx < len)
            lua_pushnumber(l, uint8_t(s[idx]));
        else
            lua_pushnil(l);
    }
    return count;
}

static int pico8_split(lua_State *l) {
    if (!lua_isstring(l, 1)) {
        return 0;
    }
    size_t count = 0, hlen;
    char const *haystack = luaL_checklstring(l, 1, &hlen);
    if (!haystack)
        return 0;
    lua_newtable(l);
    // Split either by chunk size or by needle position
    int size = 0;
    char needle = ',';
    int type = lua_type(l, 2);
    if (type == LUA_TNUMBER) {
        size = int(lua_tonumber(l, 2));
        if (size <= 0)
            size = 1;
    } else if (type == LUA_TSTRING) {
        needle = *lua_tostring(l, 2);
    }
    auto convert = lua_isnone(l, 3) || lua_toboolean(l, 3);
    char const *end = haystack + hlen + (!size && needle);
    for (char const *parser = haystack; parser < end; ) {
        lua_Number num;
        char const *next = size ? parser + size
                         : needle ? (char const*)memchr(parser, needle, end - parser) : parser + 1;
        if (!next || next > end)
            next = haystack + hlen;
        char saved = *next; // temporarily put a null terminator here
        *(char *)next = '\0';
        if (convert && luaO_str2d(parser, next - parser, &num))
            lua_pushnumber(l, num);
        else
            lua_pushlstring(l, parser, next - parser);
        *(char *)next = saved;
        lua_rawseti(l, -2, int(++count));
        parser = next + (!size && needle);
    }
    return 1;
}

extern int (*lua_strlib_sub) (lua_State *L);

static int pico8_sub(lua_State* l) {
    if (!lua_isstring(l, 1)) {
        return 0;
    }
    return lua_strlib_sub(l);
}

static int pico8_add(lua_State* l) {
    int nargs = lua_gettop(l);
    if (nargs < 2 || !lua_istable(l, 1)) {
        return 0;
    }
    int end = luaL_len(l, 1) + 1;
    int pos = end;
    if (nargs >= 3) {
        pos = luaL_checkint(l, 3);
        luaL_argcheck(l, 1 <= pos && pos <= end, 2, "position out of bounds");
        
        for (int i = end; i > pos; i--) {  /* move up elements */
            lua_rawgeti(l, 1, i-1);
            lua_rawseti(l, 1, i);  /* t[i] = t[i-1] */
        }

        lua_pushvalue(l, 2);
    }

    lua_pushvalue(l, -1); // save for return
    lua_rawseti(l, 1, pos);  /* t[pos] = v */
    return 1;
}

static int finish_deli(lua_State *l, int idx, int pos, int size) {
    lua_rawgeti(l, idx, pos);  /* result = t[pos] */
    for ( ; pos < size; pos++) {
        lua_rawgeti(l, idx, pos+1);
        lua_rawseti(l, idx, pos);  /* t[pos] = t[pos+1] */
    }
    lua_pushnil(l);
    lua_rawseti(l, idx, pos);  /* t[pos] = nil */
    return 1;
}

static int pico8_deli(lua_State *l) {
    if (!lua_istable(l, 1)) {
        return 0;
    }

    int size = luaL_len(l, 1);
    int pos = size;
    if (lua_gettop(l) >= 2)
        pos = lua_tointeger(l, 2);
    if (!(pos >= 1 && pos <= size))
        return 0;
    
    return finish_deli(l, 1, pos, size);
}

static int pico8_del(lua_State *l) {
    if (!lua_istable(l, 1) || lua_gettop(l) < 2) {
        return 0;
    }

    int size = luaL_len(l, 1);
    for (int i = 1; i <= size; i++) {
        lua_rawgeti(l, 1, i);
        if (lua_compare(l, -1, 2, LUA_OPEQ))
            return finish_deli(l, 1, i, size);
        lua_pop(l, 1);
    }
    return 0;
}

static int pico8_count(lua_State *l) {
    if (!lua_istable(l, 1)) {
        return 0;
    } else if (lua_gettop(l) == 1) {
        lua_pushinteger(l, luaL_len(l, 1));
        return 1;
    }

    int size = luaL_len(l, 1);
    int count = 0;
    for (int i = 1; i <= size; i++) {
        lua_rawgeti(l, 1, i);
        if (lua_compare(l, -1, 2, LUA_OPEQ))
            count++;
        lua_pop(l, 1);
    }
    lua_pushinteger(l, count);
    return 1;
}

static int inner_all(lua_State *l, int uv_table, int uv_idx, int uv_prev, int* ended) {
    if (lua_isnil(l, uv_table)) {
        lua_pushnil(l);
        return 1;
    }

    int idx = lua_tointeger(l, uv_idx);
    lua_pushinteger(l, idx);
    lua_gettable(l, uv_table);
    
    if (lua_compare(l, -1, uv_prev, LUA_OPEQ)) {
        lua_pop(l, 1);
        int size = luaL_len(l, uv_table);

        while (1) {
            idx++;
            if (idx > size) {
                lua_pushnil(l);
                if (ended) *ended = 1;
                break;
            }

            lua_pushinteger(l, idx);
            lua_gettable(l, uv_table);
            if (!lua_isnil(l, -1))
                break;
            lua_pop(l, 1);
        }
    }
    
    // -1 is the value to return
    lua_pushinteger(l, idx);
    lua_replace(l, uv_idx);
    lua_pushvalue(l, -1);
    lua_replace(l, uv_prev);
    return 1;
}

static int pico8_all_closure(lua_State *l) {
    return inner_all(l, lua_upvalueindex(1), lua_upvalueindex(2), lua_upvalueindex(3), NULL);
}

static int pico8_all(lua_State *l) {
    lua_pushvalue(l, 1);
    lua_pushinteger(l, 1);
    lua_pushnil(l);
    lua_pushcclosure(l, pico8_all_closure, 3);
    return 1;
}

static int pico8_foreach(lua_State *l) {
    lua_settop(l, 2);
    lua_pushvalue(l, 1);
    lua_pushinteger(l, 1);
    lua_pushnil(l);

    int ended = 0;
    while (1) {
        inner_all(l, 3, 4, 5, &ended);
        if (ended)
            break;
        
        lua_pushvalue(l, 2);
        lua_insert(l, -2);
        lua_call(l, 1, 0);
    }
    return 0;
}

static int pico8_peek_n(lua_State *l, int count) {
    unsigned int addr = lua_tonumber(l, 1);
    if (lua_gettop(l) >= 2) {
        int npeek = lua_tointeger(l, 2);
        lua_checkstack(l, npeek);
        for (int i = 0; i < npeek; i++) {
            lua_pushnumber(l, lua_pico8peek(l, addr, count));
            addr += count;
        }
        return npeek;
    } else {
        lua_pushnumber(l, lua_pico8peek(l, addr, count));
        return 1;
    }
}

static int pico8_peek(lua_State *l) {
    return pico8_peek_n(l, 1);
}
static int pico8_peek2(lua_State *l) {
    return pico8_peek_n(l, 2);
}
static int pico8_peek4(lua_State *l) {
    return pico8_peek_n(l, 4);
}

static int pico8_poke_n(lua_State *l, int count) {
    unsigned int addr = lua_tonumber(l, 1);
    int nargs = lua_gettop(l);
    if (nargs >= 3) {
        for (int i = 2; i <= nargs; i++) {
            lua_pico8poke(l, addr, count, lua_tonumber(l, i));
            addr += count;
        }
    } else {
        lua_pico8poke(l, addr, count, lua_tonumber(l, 2));
    }

    lua_pushinteger(l, 0); // always?
    return 1;
}

static int pico8_poke(lua_State *l) {
    return pico8_poke_n(l, 1);
}
static int pico8_poke2(lua_State *l) {
    return pico8_poke_n(l, 2);
}
static int pico8_poke4(lua_State *l) {
    return pico8_poke_n(l, 4);
}

static int pico8_memcpy(lua_State *l) {
    unsigned int daddr = lua_tonumber(l, 1);
    unsigned int saddr = lua_tonumber(l, 2);
    int count = lua_tointeger(l, 3);

    if (count > 0) {
        daddr &= 0xffff;
        saddr &= 0xffff;
        if (daddr > saddr && daddr < saddr + count) { // TODO: insufficient check (but so is pico8's...)
            daddr += count;
            saddr += count;
            for (int i = 0; i < count; i++) {
                lua_Number val = lua_pico8peek(l, --saddr, 1);
                lua_pico8poke(l, --daddr, 1, val);
            }
        } else {
            for (int i = 0; i < count; i++) {
                lua_Number val = lua_pico8peek(l, saddr++, 1);
                lua_pico8poke(l, daddr++, 1, val);
            }
        }
    }
    return 0;
}

static int pico8_memset(lua_State *l) {
    unsigned int addr = lua_tonumber(l, 1);
    int val = lua_tointeger(l, 2);
    int count = lua_tointeger(l, 3);

    for (int i = 0; i < count; i++) {
        lua_pico8poke(l, addr++, 1, val);
    }
    return 0;
}

extern int (*lua_baselib_assert) (lua_State *L);
extern int (*lua_baselib_getmetatable) (lua_State *L);
extern int (*lua_baselib_setmetatable) (lua_State *L);
extern int (*lua_baselib_ipairs) (lua_State *L);
extern int (*lua_baselib_inext) (lua_State *L);
extern int (*lua_baselib_next) (lua_State *L);
extern int (*lua_baselib_pairs) (lua_State *L);
extern int (*lua_baselib_rawequal) (lua_State *L);
extern int (*lua_baselib_rawlen) (lua_State *L);
extern int (*lua_baselib_rawget) (lua_State *L);
extern int (*lua_baselib_rawset) (lua_State *L);
extern int (*lua_baselib_select) (lua_State *L);
extern int (*lua_baselib_type) (lua_State *L);
extern int (*lua_tablib_pack) (lua_State *L);
extern int (*lua_tablib_unpack) (lua_State *L);
extern int (*lua_corolib_cocreate) (lua_State *L);
extern int (*lua_corolib_coresume) (lua_State *L);
extern int (*lua_corolib_costatus) (lua_State *L);
extern int (*lua_corolib_yield) (lua_State *L);

static const luaL_Reg pico8lib[] = {
  {"max",   pico8_max},
  {"min",   pico8_min},
  {"mid",   pico8_mid},
  {"ceil",  pico8_ceil},
  {"flr",   pico8_flr},
  {"cos",   pico8_cos},
  {"sin",   pico8_sin},
  {"atan2", pico8_atan2},
  {"sqrt",  pico8_sqrt},
  {"abs",   pico8_abs},
  {"sgn",   pico8_sgn},
  {"band",  pico8_band},
  {"bor",   pico8_bor},
  {"bxor",  pico8_bxor},
  {"bnot",  pico8_bnot},
  {"shl",   pico8_shl},
  {"shr",   pico8_shr},
  {"lshr",  pico8_lshr},
  {"rotl",  pico8_rotl},
  {"rotr",  pico8_rotr},
  {"tostr", pico8_tostr},
  {"tonum", pico8_tonum},
  {"chr",   pico8_chr},
  {"ord",   pico8_ord},
  {"split", pico8_split},
  {"sub",   pico8_sub},
  {"add",   pico8_add},
  {"deli",  pico8_deli},
  {"del",   pico8_del},
  {"count", pico8_count},
  {"all",   pico8_all},
  {"foreach",pico8_foreach},
  {"pack",  lua_tablib_pack},
  {"unpack",lua_tablib_unpack},
  {"cocreate", lua_corolib_cocreate},
  {"coresume", lua_corolib_coresume},
  {"costatus", lua_corolib_costatus},
  {"yield", lua_corolib_yield},
  {"inext", lua_baselib_inext},
  {"ipairs", lua_baselib_ipairs},
  {"next", lua_baselib_next},
  {"pairs", lua_baselib_pairs},
  {"rawequal", lua_baselib_rawequal},
  {"rawlen", lua_baselib_rawlen},
  {"rawget", lua_baselib_rawget},
  {"rawset", lua_baselib_rawset},
  {"select", lua_baselib_select},
  {"type", lua_baselib_type},
  {"assert", lua_baselib_assert},
  {"getmetatable", lua_baselib_getmetatable},
  {"setmetatable", lua_baselib_setmetatable},
  {"peek", pico8_peek},
  {"peek2", pico8_peek2},
  {"peek4", pico8_peek4},
  {"poke", pico8_poke},
  {"poke2", pico8_poke2},
  {"poke4", pico8_poke4},
  {"memcpy", pico8_memcpy},
  {"memset", pico8_memset},
  {NULL, NULL}
};


/*
** Register PICO-8 functions in global table
*/
LUAMOD_API int luaopen_pico8 (lua_State *L) {
  lua_pushglobaltable(L);
  luaL_setfuncs(L, pico8lib, 0);
  return 1;
}
